type AnimeItem = {
  titleZh: string
  titleEn: string
  score: number
}

type Data = {
  [key: string]: AnimeItem[]
}

const data: Data = {
  "2006": [
    { titleZh: "死亡笔记", titleEn: "Death Note", score: 8.4 },
    { titleZh: "银魂", titleEn: "Gintama", score: 8.7 },
    { titleZh: "寒蝉鸣泣之时", titleEn: "Higurashi When They Cry", score: 8 },
    {
      titleZh: "Code Geass 反叛的鲁路修",
      titleEn: "Code Geass: Lelouch of the Rebellion",
      score: 8.3,
    },
    { titleZh: "欢迎加入NHK！", titleEn: "Welcome to the N.H.K.", score: 8.2 },
    { titleZh: "Fate/stay night", titleEn: "Fate/stay night", score: 7.1 },
    {
      titleZh: "凉宫春日的忧郁",
      titleEn: "The Melancholy of Haruhi Suzumiya",
      score: 8.2,
    },
    { titleZh: "零之使魔", titleEn: "The Familiar of Zero", score: 7 },
    { titleZh: "黑礁", titleEn: "Black Lagoon", score: 7.8 },
    { titleZh: "Kanon", titleEn: "Kanon", score: 7.7 },
    { titleZh: "娜娜", titleEn: "NANA", score: 8 },
    { titleZh: "×××HOLiC", titleEn: "×××HOLiC", score: 7.8 },
    {
      titleZh: "家庭教师HITMAN REBORN!",
      titleEn: "Katekyo Hitman Reborn!",
      score: 7.5,
    },
    {
      titleZh: "樱兰高校男公关部",
      titleEn: "Ouran High School Host Club",
      score: 7.6,
    },
    { titleZh: "蜂蜜与四叶草II", titleEn: "Honey and Clover II", score: 8.5 },
  ],
  "2007": [
    { titleZh: "幸运星", titleEn: "Lucky Star", score: 8.3 },
    { titleZh: "CLANNAD", titleEn: "CLANNAD", score: 8.3 },
    {
      titleZh: "天元突破 红莲螺岩",
      titleEn: "Tengen Toppa Gurren Lagann",
      score: 8.6,
    },
    { titleZh: "旋风管家", titleEn: "Hayate the Combat Butler", score: 7.4 },
    { titleZh: "火影忍者疾风传", titleEn: "Naruto Shippuden", score: 7.6 },
    { titleZh: "悠久之翼", titleEn: "ef: A Tale of Memories", score: 7.9 },
    { titleZh: "赌博默示录", titleEn: "Kaiji: Ultimate Survivor", score: 7.9 },
    { titleZh: "永生之酒", titleEn: "Baccano!", score: 8.2 },
    { titleZh: "机动战士高达00", titleEn: "Mobile Suit Gundam 00", score: 7.6 },
    {
      titleZh: "再见绝望先生",
      titleEn: "Sayonara, Zetsubou-Sensei",
      score: 7.8,
    },
    { titleZh: "日在校园", titleEn: "School Days", score: 6.3 },
    { titleZh: "南家三姐妹", titleEn: "Minami-ke", score: 7.6 },
    {
      titleZh: "DARKER THAN BLACK -黑之契约者-",
      titleEn: "Darker than Black",
      score: 8,
    },
    { titleZh: "濑户的花嫁", titleEn: "My Bride is a Mermaid", score: 7.4 },
    { titleZh: "电脑线圈", titleEn: "Dennō Coil", score: 8.1 },
    { titleZh: "物怪", titleEn: "Mononoke", score: 8.2 },
    { titleZh: "向阳素描", titleEn: "Hidamari Sketch", score: 7.5 },
    {
      titleZh: "零之使魔 双月骑士",
      titleEn: "The Familiar of Zero: Knight of the Twin Moons",
      score: 6.9,
    },
    { titleZh: "sola", titleEn: "Sola", score: 7.2 },
  ],
  "2008": [
    { titleZh: "出包王女", titleEn: "To Love-Ru", score: 6.9 },
    { titleZh: "龙与虎", titleEn: "Toradora!", score: 8 },
    { titleZh: "魔法禁书目录", titleEn: "A Certain Magical Index", score: 6.8 },
    { titleZh: "狼与香辛料", titleEn: "Spice and Wolf", score: 7.8 },
    { titleZh: "夏目友人帐", titleEn: "Natsume's Book of Friends", score: 8 },
    { titleZh: "真实之泪", titleEn: "True Tears", score: 7.5 },
    { titleZh: "神薙", titleEn: "Kannagi", score: 7.1 },
    { titleZh: "我的狐仙女友", titleEn: "Kanokon", score: 6.1 },
    { titleZh: "噬魂师", titleEn: "Soul Eater", score: 7.4 },
    { titleZh: "黑执事", titleEn: "Black Butler", score: 7 },
    {
      titleZh: "俗・再见绝望先生",
      titleEn: "Zoku Sayonara Zetsubou Sensei",
      score: 7.8,
    },
    { titleZh: "鹡鸰女神", titleEn: "Sekirei", score: 6.2 },
    { titleZh: "强袭魔女", titleEn: "Strike Witches", score: 7.1 },
  ],
  "2009": [
    { titleZh: "轻音少女", titleEn: "K-ON!", score: 8.2 },
    {
      titleZh: "钢之炼金术师 FULLMETAL ALCHEMIST",
      titleEn: "Fullmetal Alchemist: Brotherhood",
      score: 8.8,
    },
    { titleZh: "化物语", titleEn: "Bakemonogatari", score: 8.4 },
    {
      titleZh: "凉宫春日的忧郁 2009",
      titleEn: "The Melancholy of Haruhi Suzumiya (2009)",
      score: 8,
    },
    {
      titleZh: "某科学的超电磁炮",
      titleEn: "A Certain Scientific Railgun",
      score: 7.5,
    },
    {
      titleZh: "学生会的一己之见",
      titleEn: "Student Council's Discretion",
      score: 7.4,
    },
    { titleZh: "天降之物", titleEn: "Heaven's Lost Property", score: 7.3 },
    { titleZh: "天才麻将少女", titleEn: "Saki", score: 7.5 },
    { titleZh: "白色相簿", titleEn: "White Album", score: 7.3 },
    { titleZh: "妖精的尾巴", titleEn: "Fairy Tail", score: 7.4 },
    { titleZh: "好想告诉你", titleEn: "Kimi ni Todoke", score: 7.6 },
  ],
  "2010": [
    {
      titleZh: "吊带袜天使",
      titleEn: "Panty & Stocking with Garterbelt",
      score: 8,
    },
    { titleZh: "四叠半神话大系", titleEn: "The Tatami Galaxy", score: 8.6 },
    { titleZh: "妄想学生会", titleEn: "Seitokai Yakuindomo", score: 7.5 },
    { titleZh: "缘之空", titleEn: "Yosuga no Sora", score: 6.6 },
    { titleZh: "笨蛋，测验，召唤兽", titleEn: "Baka and Test", score: 7.4 },
    { titleZh: "天使的心跳！", titleEn: "Angel Beats!", score: 7.5 },
    { titleZh: "无头骑士异闻录", titleEn: "Durarara!!", score: 7.9 },
    {
      titleZh: "只有神知道的世界",
      titleEn: "The World God Only Knows",
      score: 7.2,
    },
    { titleZh: "圣诞之吻SS", titleEn: "Amagami SS", score: 7.3 },
    { titleZh: "我的妹妹哪有这么可爱！", titleEn: "Oreimo", score: 7.1 },
    { titleZh: "女仆咖啡厅", titleEn: "And Yet the Town Moves", score: 7.8 },
    { titleZh: "亲吻姐姐", titleEn: "Kiss × Sis", score: 6.7 },
    { titleZh: "迷糊餐厅", titleEn: "Working!", score: 7.5 },
    {
      titleZh: "学园默示录 HIGHSCHOOL OF THE DEAD",
      titleEn: "High School of the Dead",
      score: 6.7,
    },
    { titleZh: "荒川爆笑团", titleEn: "Arakawa Under the Bridge", score: 7.5 },
    { titleZh: "天降之物f", titleEn: "Heaven's Lost Property f", score: 7.3 },
    { titleZh: "爆漫王。", titleEn: "Bakuman", score: 8 },
    { titleZh: "会长是女仆大人！", titleEn: "Maid Sama!", score: 6.9 },
    { titleZh: "圣痕炼金士", titleEn: "Seikon no Qwaser", score: 6 },
    { titleZh: "空之音", titleEn: "Sound of the Sky", score: 6.8 },
  ],
  "2011": [
    { titleZh: "命运石之门", titleEn: "Steins;Gate", score: 8.8 },
    { titleZh: "日常", titleEn: "Nichijou", score: 8.5 },
    { titleZh: "Fate/Zero", titleEn: "Fate/Zero", score: 8.1 },
    {
      titleZh: "魔法少女小圆",
      titleEn: "Puella Magi Madoka Magica",
      score: 8.6,
    },
    { titleZh: "回转企鹅罐", titleEn: "Penguindrum", score: 8 },
    { titleZh: "摇曳百合", titleEn: "YuruYuri", score: 7.6 },
    {
      titleZh: "我们仍未知道那天所看见的花的名字。",
      titleEn: "AnoHana",
      score: 7.6,
    },
    { titleZh: "罪恶王冠", titleEn: "Guilty Crown", score: 6.5 },
    { titleZh: "花开伊吕波", titleEn: "Hanasaku Iroha", score: 7.5 },
    { titleZh: "偶像大师", titleEn: "The Idolmaster", score: 8.3 },
    { titleZh: "GOSICK", titleEn: "GOSICK", score: 7.3 },
    { titleZh: "我的朋友很少", titleEn: "Haganai", score: 6.8 },
    { titleZh: "猎人", titleEn: "Hunter x Hunter", score: 8.2 },
    { titleZh: "未来日记", titleEn: "Future Diary", score: 7.2 },
    {
      titleZh: "电波女与青春男",
      titleEn: "Ground Control to Psychoelectric Girl",
      score: 7.1,
    },
    { titleZh: "这个是僵尸吗？", titleEn: "Is This a Zombie?", score: 6.8 },
    {
      titleZh: "赌博默示录 破戒录篇",
      titleEn: "Kaiji: Against All Rules",
      score: 7.8,
    },
    { titleZh: "迷茫管家与懦弱的我", titleEn: "Mayo Chiki!", score: 6.6 },
    { titleZh: "纯白交响曲", titleEn: "Mashiro-iro Symphony", score: 6.5 },
    { titleZh: "神的记事本", titleEn: "Heaven's Memo Pad", score: 6.7 },
    { titleZh: "BLOOD-C", titleEn: "BLOOD-C", score: 6 },
    {
      titleZh: "丹特丽安的书架",
      titleEn: "The Mystic Archives of Dantalian",
      score: 7.1,
    },
  ],
  "2012": [
    { titleZh: "冰菓", titleEn: "Hyouka", score: 8.2 },
    {
      titleZh: "JOJO的奇妙冒险",
      titleEn: "JoJo's Bizarre Adventure",
      score: 7.8,
    },
    {
      titleZh: "男子高中生的日常",
      titleEn: "Daily Lives of High School Boys",
      score: 7.9,
    },
    {
      titleZh: "中二病也要谈恋爱！",
      titleEn: "Love, Chunibyo & Other Delusions!",
      score: 7.4,
    },
    { titleZh: "来自新世界", titleEn: "From the New World", score: 8.2 },
    { titleZh: "伪物语", titleEn: "Nisemonogatari", score: 7.8 },
    { titleZh: "Another", titleEn: "Another", score: 7 },
    {
      titleZh: "樱花庄的宠物女孩",
      titleEn: "The Pet Girl of Sakurasou",
      score: 7.4,
    },
    { titleZh: "心理测量者", titleEn: "Psychi-Pass", score: 7.9 },
    { titleZh: "恶魔高校 D×D", titleEn: "High School DxD", score: 6.9 },
    { titleZh: "刀剑神域", titleEn: "Sword Art Online", score: 7.3 },
    { titleZh: "人类衰退之后", titleEn: "Humanity Has Declined", score: 7.9 },
    { titleZh: "Little Busters!", titleEn: "Little Busters!", score: 7.1 },
    {
      titleZh: "潜行吧！奈亚子",
      titleEn: "Nyaruko: Crawling with Love",
      score: 7,
    },
    { titleZh: "邻座的怪同学", titleEn: "My Little Monster", score: 7.2 },
    { titleZh: "猫物语（黑）", titleEn: "Nekomonogatari (Black)", score: 7.7 },
    { titleZh: "少女与战车", titleEn: "Girls und Panzer", score: 7.6 },
    { titleZh: "心灵链环", titleEn: "Kokoro Connect", score: 7.4 },
    { titleZh: "TARI TARI", titleEn: "TARI TARI", score: 7.3 },
    { titleZh: "谜样女友X", titleEn: "Mysterious Girlfriend X", score: 7 },
    { titleZh: "就算是哥哥只要有爱就没问题对吧", titleEn: "OniAi", score: 5.9 },
    { titleZh: "散华礼弥", titleEn: "Sankarea: Undying Love", score: 6.8 },
  ],
  "2013": [
    { titleZh: "进击的巨人", titleEn: "Attack on Titan", score: 8.2 },
    { titleZh: "斩服少女", titleEn: "Kill la Kill", score: 8.1 },
    {
      titleZh: "我的青春恋爱物语果然有问题",
      titleEn: "My Teen Romantic Comedy SNAF",
      score: 7.5,
    },
    { titleZh: "悠哉日常大王", titleEn: "Non Non Biyori", score: 8 },
    { titleZh: "玉子市场", titleEn: "Tamako Market", score: 7.2 },
    { titleZh: "向山进发", titleEn: "Yama no Susume", score: 7.1 },
    { titleZh: "约会大作战", titleEn: "Date A Live", score: 6.6 },
    { titleZh: "噬血狂袭", titleEn: "Strike the Blood", score: 6.6 },
    {
      titleZh: "来自风平浪静的明天",
      titleEn: "Nagi-Asu: A Lull in the Sea",
      score: 7.5,
    },
    { titleZh: "我的妹妹哪有这么可爱。2", titleEn: "Oreimo 2", score: 6.9 },
    {
      titleZh: "我不受欢迎，怎么想都是你们的错！",
      titleEn: "WataMote",
      score: 6.9,
    },
    { titleZh: "境界的彼方", titleEn: "Beyond the Boundary", score: 6.8 },
    {
      titleZh: "我的脑内选项正在全力妨碍学园恋爱喜剧",
      titleEn:
        "My Brain's Little Options Are Doing Their Best to Hinder My School Romance Comedy",
      score: 6.6,
    },
    {
      titleZh: "Fate/kaleid liner 魔法少女☆伊莉雅",
      titleEn: "Fate/kaleid liner 魔法少女☆イリヤ",
      score: 6.9,
    },
    { titleZh: "GJ部", titleEn: "GJ Club", score: 6.9 },
    {
      titleZh: "弹丸论破 希望学园与绝望高中生",
      titleEn: "Danganronpa: The Animation",
      score: 6.6,
    },
    { titleZh: "黄金拼图", titleEn: "Golden Time", score: 7.3 },
    { titleZh: "Love Live!", titleEn: "Love Live!", score: 7.2 },
    {
      titleZh: "我女友与青梅竹马的惨烈修罗场",
      titleEn: "Oreshura",
      score: 6.4,
    },
    { titleZh: "我的朋友很少NEXT", titleEn: "Haganai NEXT", score: 6.7 },
  ],
  "2014": [
    { titleZh: "白箱", titleEn: "Shirobako", score: 8.7 },
    { titleZh: "四月是你的谎言", titleEn: "Your Lie in April", score: 8 },
    {
      titleZh: "Fate/stay night [Unlimited Blade Works]",
      titleEn: "Fate/stay night [Unlimited Blade Works]",
      score: 7.5,
    },
    { titleZh: "游戏人生", titleEn: "No Game No Life", score: 7.7 },
    { titleZh: "乒乓", titleEn: "Ping Pong", score: 8.7 },
    { titleZh: "甘城光辉游乐园", titleEn: "Amagi Brilliant Park", score: 7 },
    { titleZh: "寄生兽 生命的准则", titleEn: "Parasyte -the maxim-", score: 8 },
    { titleZh: "伪恋", titleEn: "Nisekoi", score: 7.1 },
    {
      titleZh: "月刊少女野崎君",
      titleEn: "Monthly Girls' Nozaki-kun",
      score: 7.8,
    },
    {
      titleZh: "请问您今天要来点兔子吗？",
      titleEn: "Is the Order a Rabbit?",
      score: 7.3,
    },
    { titleZh: "斩·赤红之瞳！", titleEn: "Akame ga Kill!", score: 6.6 },
    { titleZh: "太空丹迪", titleEn: "Space Dandy", score: 8 },
    { titleZh: "妄想学生会＊", titleEn: "Seitokai Yakuindomo", score: 7.6 },
    { titleZh: "东京喰种", titleEn: "Tokyo Ghoul", score: 6.7 },
    { titleZh: "凭物语", titleEn: "Owarimonogatari: End Tale", score: 7.5 },
    { titleZh: "灰色的果实", titleEn: "The Fruit of Grisaia", score: 7.1 },
    { titleZh: "花物语", titleEn: "Hanamonogatari ", score: 7.3 },
    { titleZh: "农林", titleEn: "Nourin", score: 6.6 },
    {
      titleZh: "魔法科高校的劣等生",
      titleEn: "The Irregular at Magic High School",
      score: 5.8,
    },
    { titleZh: "野良神", titleEn: "Noragami", score: 7.1 },
  ],
  "2015": [
    {
      titleZh: "路人女主的养成方法",
      titleEn: "Saekano: How to Raise a Boring Girlfriend",
      score: 7.2,
    },
    { titleZh: "暗杀教室", titleEn: "Assassination Classroom", score: 7.3 },
    { titleZh: "一拳超人", titleEn: "One Punch Man", score: 8 },
    {
      titleZh: "新妹魔王的契约者",
      titleEn: "The Testament of Sister New Devil",
      score: 5.8,
    },
    { titleZh: "夏洛特", titleEn: "Charlotte", score: 6.3 },
    { titleZh: "OVERLORD", titleEn: "Overlord", score: 6.9 },
    { titleZh: "监狱学园", titleEn: "Prison School", score: 7.3 },
    { titleZh: "可塑性记忆", titleEn: "Plastic Memories", score: 7 },
    {
      titleZh: "在地下城寻求邂逅是否搞错了什么",
      titleEn: "Is it wrong to Try to Pick Up Girls in a Dungeon?",
      score: 6.8,
    },
    { titleZh: "干物妹！小埋", titleEn: "Himouto! Umaru-chan", score: 6.8 },
    { titleZh: "吹响！悠风号", titleEn: "Sound! Euphonium", score: 8.3 },
    { titleZh: "终物语", titleEn: "Owarimonogatari", score: 7.8 },
    { titleZh: "旋转少女", titleEn: "The Rolling Girls", score: 7.4 },
    {
      titleZh: "落第骑士英雄谭",
      titleEn: "Chivalry of a Failed Knight",
      score: 6.5,
    },
    { titleZh: "没有黄段子存在的无聊世界", titleEn: "Shimoneta", score: 6.1 },
  ],
  "2016": [
    { titleZh: "为美好的世界献上祝福！", titleEn: "Kono Suba", score: 7.6 },
    { titleZh: "3月的狮子", titleEn: "March Comes in Like a Lion", score: 8.3 },
    { titleZh: "ReLIFE", titleEn: "ReLIFE", score: 7.7 },
    {
      titleZh: "齐木楠雄的灾难",
      titleEn: "The Disastrous Life of Saiki K.",
      score: 7.7,
    },
    { titleZh: "Re：从零开始的异世界生活", titleEn: "Re:Zero ", score: 7.4 },
    { titleZh: "只有我不存在的城市", titleEn: "Erased", score: 7.7 },
    { titleZh: "灵能百分百", titleEn: "Mob Psycho 100", score: 7.8 },
    {
      titleZh: "灰与幻想的格林姆迦尔",
      titleEn: "Grimgar of Fantasy and Ash",
      score: 7.5,
    },
    {
      titleZh: "这个美术社大有问题！",
      titleEn: "This Art Club Has a Problem!",
      score: 7.3,
    },
    { titleZh: "轻拍翻转小魔女", titleEn: "Flip Flappers", score: 7.5 },
    { titleZh: "飞翔的魔女", titleEn: "Flying Witch", score: 7.5 },
    { titleZh: "NEW GAME!", titleEn: "NEW GAME!", score: 7.4 },
    {
      titleZh: "在下坂本，有何贵干？",
      titleEn: "Haven't You Heard? I'm Sakamoto",
      score: 6.5,
    },
    {
      titleZh: "昭和元禄落语心中",
      titleEn: "Descending Stories: Showa Genroku Rakugo Shinju",
      score: 8.2,
    },
    {
      titleZh: "无彩限的怪灵世界",
      titleEn: "Myriad Colors Phantom World",
      score: 6.2,
    },
    {
      titleZh: "线上游戏的老婆不可能是女生？",
      titleEn: "And You Thought There Is Never a Girl Online? ",
      score: 6,
    },
    { titleZh: "亚人", titleEn: "Ajin: Demi-Human", score: 7.3 },
    {
      titleZh: "甲铁城的卡巴内利",
      titleEn: "Kabaneri of the Iron Fortress",
      score: 5.9,
    },
    { titleZh: "剑风传奇", titleEn: "Berserk", score: 6.8 },
  ],
  "2017": [
    { titleZh: "少女终末旅行", titleEn: "Girls' Last Tour", score: 8.1 },
    { titleZh: "来自深渊", titleEn: "Made in Abyss", score: 8.2 },
    {
      titleZh: "小林家的龙女仆",
      titleEn: "Miss Kobayashi's Dragon Maid",
      score: 7.4,
    },
    { titleZh: "狂赌之渊", titleEn: "Kakegurui", score: 7 },
    {
      titleZh: "末日时在做什么？有没有空？可以来拯救吗？",
      titleEn: "WorldEnd",
      score: 7.6,
    },
    { titleZh: "月色真美", titleEn: "Tsuki ga Kirei", score: 7.9 },
    { titleZh: "重启咲良田", titleEn: "Sagrada Reset", score: 7.9 },
    { titleZh: "BanG Dream!", titleEn: "BanG Dream!", score: 6.4 },
    { titleZh: "幼女战记", titleEn: "Saga of Tanya the Evil", score: 7.2 },
    { titleZh: "小魔女学园", titleEn: "Little Witch Academia", score: 7.7 },
    { titleZh: "Just Because!", titleEn: "Just Because!", score: 7.3 },
    { titleZh: "埃罗芒阿老师", titleEn: "Eromanga Sensei", score: 6.6 },
    { titleZh: "人渣的本愿", titleEn: "Scum's Wish", score: 6.6 },
    { titleZh: "珈百璃的堕落", titleEn: "Gabriel DropOut", score: 7.1 },
    { titleZh: "笨女孩", titleEn: "Aho-Girl", score: 6.6 },
    { titleZh: "黑色五叶草", titleEn: "Black Clover", score: 6.5 },
    {
      titleZh: "如果有妹妹就好了。",
      titleEn: "A Sister's All You Need",
      score: 6.6,
    },
    { titleZh: "徒然喜欢你", titleEn: "Tsuredure Children", score: 7.1 },
    {
      titleZh: "不正经的魔术讲师与禁忌教典",
      titleEn: "Akashic Records of Bastard Magic Instructor",
      score: 6.2,
    },
  ],
  "2018": [
    { titleZh: "摇曳露营△", titleEn: "Yuru Camp△", score: 8.2 },
    { titleZh: "碧蓝之海", titleEn: "Grand Blue", score: 7.8 },
    {
      titleZh: "赛马娘 Pretty Derby",
      titleEn: "Umamusume Pretty Derby",
      score: 7,
    },
    { titleZh: "紫罗兰永恒花园", titleEn: "Violet Evergarden", score: 7.5 },
    { titleZh: "强风吹拂", titleEn: "Run with the Wind", score: 8.3 },
    {
      titleZh: "少女☆歌剧 Revue Starlight",
      titleEn: "Shōjo☆gekijō Revue Starlight",
      score: 7.9,
    },
    {
      titleZh: "擅长捉弄的高木同学",
      titleEn: "Teasing Master Takagi-san",
      score: 7.5,
    },
    { titleZh: "佐贺偶像是传奇", titleEn: "Zombie Land Saga", score: 7.8 },
    {
      titleZh: "比宇宙更远的地方",
      titleEn: "A Place Further Than the Universe",
      score: 8.2,
    },
    {
      titleZh: "青春笨蛋少年不做兔女郎学姐的梦",
      titleEn: "Rascal Does Not Dream of Bunny Girl Senpai",
      score: 7.4,
    },
    { titleZh: "哥布林杀手", titleEn: "Goblin Slayer", score: 6.7 },
    { titleZh: "终将成为你", titleEn: "Bloom into You", score: 7.8 },
    {
      titleZh: "DARLING in the FRANXX",
      titleEn: "DARLING in the FRANXX",
      score: 6.2,
    },
    { titleZh: "来玩游戏吧", titleEn: "Gamers!", score: 7.6 },
    { titleZh: "邪神与厨二病少女", titleEn: "Dropkick on My Devil!", score: 7 },
    { titleZh: "恋如雨止", titleEn: "After the Rain", score: 7.5 },
    {
      titleZh: "关于我转生变成史莱姆这档事",
      titleEn: "That Time I Got Reincarnated as a Slime",
      score: 6.6,
    },
    { titleZh: "黄金神威", titleEn: "Golden Kamuy", score: 7.5 },
  ],
  "2019": [
    { titleZh: "冰海战记", titleEn: "Vinland Saga", score: 8.3 },
    {
      titleZh: "辉夜大小姐想让我告白～天才们的恋爱头脑战～",
      titleEn: "Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunōsen",
      score: 7.8,
    },
    { titleZh: "街角魔族", titleEn: "The Demon Girl Next Door", score: 7.5 },
    { titleZh: "鬼灭之刃", titleEn: "Demon Slayer", score: 7.3 },
    { titleZh: "炎炎消防队", titleEn: "Fire Force", score: 6.5 },
    {
      titleZh: "女高中生的无所事事",
      titleEn: "Wasteful Days of High School Girls",
      score: 7.6,
    },
    {
      titleZh: "慎重勇者 ～这个勇者明明超强却过分慎重～",
      titleEn: "Cautious Hero: ",
      score: 6.9,
    },
    { titleZh: "天使降临到了我身边！", titleEn: "Angels' 3Piece!", score: 7.3 },
    { titleZh: "不吉波普不笑", titleEn: "Boogiepop and Others", score: 7.3 },
    {
      titleZh: "笨拙之极的上野",
      titleEn: "How Clumsy You Are, Miss Ueno",
      score: 6.5,
    },
    {
      titleZh: "五等分的新娘",
      titleEn: "The Quintessential Quintuplets",
      score: 6,
    },
    { titleZh: "约定的梦幻岛", titleEn: "Yakusoku no Neverland", score: 7.6 },
    {
      titleZh: "只要可爱即使是变态你也会喜欢我吧？",
      titleEn: "Hensuki",
      score: 6.1,
    },
    {
      titleZh: "Fate/Grand Order -绝对魔兽战线巴比伦尼亚-",
      titleEn: "Fate/Grand Order -Absolute Demonic Front: Babylonia-",
      score: 6.8,
    },
    { titleZh: "家有女友", titleEn: "Kanojo, Okarishimasu", score: 6.3 },
    {
      titleZh: "君主·埃尔梅罗二世事件簿 魔眼收集列车 Grace note",
      titleEn: "The Case Files of Lord El-Melloi II: Rail Zeppelin Grace Note",
      score: 6.7,
    },
    { titleZh: "石纪元", titleEn: "Dr. Stone", score: 7.2 },
  ],
  "2020": [
    {
      titleZh: "异种族风俗娘评鉴指南",
      titleEn: "Ishuzoku Reviewers",
      score: 7.7,
    },
    {
      titleZh: "魔女之旅",
      titleEn: "Wandering Witch: The Journey of Elaina",
      score: 7.1,
    },
    { titleZh: "安达与岛村", titleEn: "Adachi and Shimamura", score: 7.3 },
    { titleZh: "异度侵入", titleEn: "ID:INVADED", score: 7.5 },
    {
      titleZh: "别对映像研出手！",
      titleEn: "Keep Your Hands Off Eizouken!",
      score: 8.1,
    },
    { titleZh: "咒术回战", titleEn: "Jujutsu Kaisen", score: 7.1 },
    {
      titleZh: "总之就是非常可爱",
      titleEn: "Tonikawa: Over the Moon For You",
      score: 6.3,
    },
    { titleZh: "隐瞒之事", titleEn: "Kakushigoto", score: 7.7 },
    { titleZh: "虚构推理", titleEn: "In/Spectre", score: 6.3 },
    { titleZh: "恋爱小行星", titleEn: "Koisuru Asteroid", score: 6.9 },
    {
      titleZh: "你与我最后的战场，亦或是世界起始的圣战",
      titleEn: "Our Last Crusade or the Rise of a New World",
      score: 5.5,
    },
    {
      titleZh: "邪神与厨二病少女' ",
      titleEn: "Dropkick on My Devil!",
      score: 7.3,
    },
    {
      titleZh: "转生成为了只有乙女游戏破灭Flag的邪恶大小姐",
      titleEn: "My Next Life as a Villainess: All Routes Lead to Doom!",
      score: 6.5,
    },
    {
      titleZh: "在魔王城说晚安",
      titleEn: "Sleepy Princess in the Demon Castle",
      score: 7,
    },
    { titleZh: "租借女友", titleEn: "Rent-A-Girlfriend", score: 5.8 },
  ],
  "2021": [
    { titleZh: "86 -不存在的战区-", titleEn: "86 -Eighty-Six-", score: 7.6 },
    {
      titleZh: "无职转生～",
      titleEn: "Mushoku Tensei: Jobless Reincarnation",
      score: 7.9,
    },
    { titleZh: "回复术士的重来人生", titleEn: "Redo of Healer", score: 6.2 },
    { titleZh: "奇巧计程车", titleEn: "Odd Taxi", score: 8.5 },
    {
      titleZh: "打了300年的史莱姆，不知不觉就练到了满级",
      titleEn: "I’ve Been Killing Slimes for 300 Years and Maxed Out My Level",
      score: 6.3,
    },
    { titleZh: "漂流少年", titleEn: "Sonny Boy", score: 7.8 },
    { titleZh: "堀与宫村", titleEn: "Horimiya", score: 6.8 },
    {
      titleZh: "派遣战斗员！",
      titleEn: "Combatants Will Be Dispatched!",
      score: 6.3,
    },
    {
      titleZh: "古见同学有交流障碍症",
      titleEn: "Komi Can't Communicate",
      score: 7,
    },
    { titleZh: "奇蛋物语", titleEn: "Wonder Egg Priority", score: 6.8 },
    { titleZh: "我们的重制人生", titleEn: "Remake Our Life!", score: 6.4 },
    { titleZh: "看得见的女孩", titleEn: "Mieruko-chan", score: 6.8 },
    {
      titleZh: "异世界迷宫黑心企业",
      titleEn: "The Dungeon of Black Company",
      score: 6.7,
    },
    {
      titleZh: "女神宿舍的宿管君。",
      titleEn: "Megami-ryō no Ryōbo-kun",
      score: 5.8,
    },
  ],
  "2022": [
    { titleZh: "孤独摇滚！", titleEn: "Bocchi the Rock!", score: 8.4 },
    { titleZh: "莉可丽丝", titleEn: "Lycoris Recoil", score: 6.3 },
    {
      titleZh: "想要成为影之实力者！",
      titleEn: "The Eminence in Shadow",
      score: 7.1,
    },
    { titleZh: "夏日重现", titleEn: "Summer Time Rendering", score: 7.5 },
    { titleZh: "异世界舅舅", titleEn: "Uncle from Another World", score: 7.6 },
    { titleZh: "更衣人偶坠入爱河", titleEn: "My Dress-Up Darling", score: 7.2 },
    { titleZh: "彻夜之歌", titleEn: "Call of the Night", score: 7.4 },
    {
      titleZh: "测不准的阿波连同学",
      titleEn: "Aharen Is Indecipherable",
      score: 6.4,
    },
    { titleZh: "间谍过家家", titleEn: "SPY×FAMILY", score: 7.2 },
    { titleZh: "不道德公会", titleEn: "Immoral Guild", score: 7.1 },
    { titleZh: "链锯人", titleEn: "Chainsaw Man", score: 6.9 },
    {
      titleZh: "明日同学的水手服",
      titleEn: "Akebi's Sailor Uniform",
      score: 7.5,
    },
    { titleZh: "契约之吻", titleEn: "Engage Kiss", score: 6.9 },
    { titleZh: "相合之物", titleEn: "Sasaki and Miyano", score: 7.8 },
  ],
  "2023": [
    {
      titleZh: "葬送的芙莉莲",
      titleEn: "Frieren: Beyond Journey's End",
      score: 8.5,
    },
    {
      titleZh: "药屋少女的呢喃",
      titleEn: "The Apothecary Diaries",
      score: 7.5,
    },
    {
      titleZh: "BanG Dream! It's MyGO!!!!!",
      titleEn: "BanG Dream! It's MyGO!!!!!",
      score: 8.1,
    },
    {
      titleZh: "我心里危险的东西",
      titleEn: "The Dangers in My Heart",
      score: 7.8,
    },
    {
      titleZh: "超超超超超喜欢你的100个女朋友",
      titleEn: "The 100 Girlfriends Who Really Love You",
      score: 7.3,
    },
    {
      titleZh: "别当欧尼酱了！",
      titleEn: "Onimai: I'm Now Your Sister!",
      score: 7.6,
    },
    { titleZh: "跃动青春", titleEn: "Skip and Loafer", score: 7.7 },
    { titleZh: "宝可梦 地平线", titleEn: "Pokémon Horizons", score: 7.5 },
    {
      titleZh: "香格里拉·弗陇提亚～屎作猎人向神作发起挑战～",
      titleEn: "Shangri-La Frontier",
      score: 6.4,
    },
    {
      titleZh: "无神世界的神明活动",
      titleEn: "KamiKatsu: Working for God in a Godless World",
      score: 6.8,
    },
    { titleZh: "我推的孩子", titleEn: "Oshi no Ko", score: 7.4 },
    { titleZh: "天国大魔境", titleEn: "Heavenly Delusion", score: 7.8 },
    {
      titleZh: "异世界悠闲农家",
      titleEn: "Farming Life in Another World",
      score: 6.4,
    },
  ],
  "2024": [
    {
      titleZh: "败犬女主太多了！",
      titleEn: "Too Many Losing Heroines!",
      score: 8,
    },
    { titleZh: "GIRLS BAND CRY", titleEn: "GIRLS BAND CRY", score: 7.6 },
    { titleZh: "胆大党", titleEn: "Dandadan", score: 7.5 },
    { titleZh: "义妹生活", titleEn: "Gimai Seikatsu", score: 7.3 },
    { titleZh: "迷宫饭", titleEn: "Delicious in Dungeon", score: 7.8 },
    { titleZh: "我独自升级", titleEn: "Solo Leveling", score: 6.5 },
    { titleZh: "小市民系列", titleEn: "Shoshimin", score: 6.1 },
    {
      titleZh: "梦想成为魔法少女",
      titleEn: "Gushing over Magical Girls",
      score: 7,
    },
    { titleZh: "青之箱", titleEn: "Blue Box", score: 6.8 },
    {
      titleZh: "2.5次元的诱惑",
      titleEn: "2.5 Dimensional Seduction",
      score: 6.7,
    },
    {
      titleZh: "地。 ―关于地球的运动―",
      titleEn: "Orb: On the Movements of the Earth",
      score: 6.2,
    },
    { titleZh: "失忆投捕", titleEn: "The Elusive Samurai", score: 7.9 },
    {
      titleZh: "不时轻声地以俄语遮羞的邻座艾莉同学",
      titleEn: "Alya Sometimes Hides Her Feelings in Russian",
      score: 5.6,
    },
    { titleZh: "悲喜渔生", titleEn: "Fisherman's Songs", score: 7.3 },
    {
      titleZh: "亚托莉 -我挚爱的时光-",
      titleEn: "Atri: My Dear Moments",
      score: 6.3,
    },
    { titleZh: "缘结甘神家", titleEn: "The Elusive Samurai", score: 5.9 },
  ],
}

// 添加一个辅助函数来根据语言获取动画标题
export const getAnimeTitle = (
  anime: AnimeItem,
  language: "zh" | "en"
): string => {
  return language === "zh" ? anime.titleZh : anime.titleEn
}

export default data
